FISH-6737 Upgrade Tool fails when domain1 has been removed and there are more than 1 domains
payara/upgrade-tool pull request #10
Opened 2022-11-23 17:14 UTC by JamesHillyard

By setting the domain name, when the initDomain method gets the domain name for the DomainDirs constructor, it bypasses the need to look for 'domain1' which has been hardcoded. Normally this would cause the command to be executed against that specific domain, but in the case of upgrade tool it will upgrade all domains anyway, so using a specific domain here doesn't change anything. This also maintains the full validation of the domains dir.

Tested with 0 domains, 1 domain, 2 domains (inc domain 1), 2 domains (no domain 1) - All scenarios worked

Pending approval, I will update this to 1.6, release to nexus, tag the release, and increment to 1.7-SNAPSHOT

2022-11-25 10:08 UTC, Pandrex247 requested changes
I found a failing case:

If the default domain dir has no entries or the default entries, you get a failure if you use a custom domain dir where the names of the domains don't match.

So, for example, in default domain dir have the usual domain1 and production, and then in a custom domains dir have two custom domains (e.g. adomain and bdomain).

When you use the upgrade server command and specify your custom domain dir you get an error stating that domain1 doesn't exist.

You hit essentially the same problem if the default domain dir is empty - it's not looking at your defined domain dir.

TLDR: like in the "original" `initDomain` method you need to account for the domaindir param.

2022-11-25 18:04 UTC, JamesHillyard commented
Tested: 
- Default domaindir, domain1 & production
- Default domaindir, production only
- Default domaindir, domain1 only
- Default domaindir, _empty_

These specify a custom domaindir with --domaindir, leaving the default dir in various states
- Custom domaindir (adomain, bdomain), default domaindir (domain1, production)
- Custom domaindir (adomain, bdomain), default domaindir (domain1)
- Custom domaindir (adomain, bdomain), default domaindir (production)
- Custom domaindir (adomain, bdomain), default domaindir _(empty)_
- Custom domaindir (domain1), default domaindir _(empty)_
- Custom domaindir (domain1), default domaindir (domain1)
- Custom domaindir _(empty)_, default domaindir (domain1, production)
- Custom domaindir _(empty)_, default domaindir _(empty)_

2022-11-25 18:04 UTC, JamesHillyard commented on src/main/java/fish/payara/extras/upgrade/BaseUpgradeCommand.java
> +             setDomainName(defaultDomainsDir.listFiles()[0].getName());
Added

2022-11-28 12:16 UTC, Pandrex247 approved these changes

2022-11-28 12:24 UTC, merged